### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by eduardsui** [SopaXorzTaker/ya25519#1]
Can you clarify the license for this code? Is this unlicensed / public domain?

**Comment by SopaXorzTaker** [comment]
I'd license it to under GPLv3, however I want to ask - what purpose do you want to use it for?

It's not resistant to timing attacks, etc - definitely not for production.

**Comment by SopaXorzTaker** [comment]
It's only for educational purposes and would not suit real-world needs.
Feel free to use it for reference, and please check out my own TLS project,
sxTLS.

It has everything working (AES, RSA and X509), but it lacks an
implementagion of the protocol.

It's kind of abandoned and I'd gladly welcome any contributions or
contribute to a project that uses its portions.
